import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import Main from "@/components/layout/Main/Main";
import SessionWrapper from "@/components/providers/SessionWrapper"; 

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn("bg-background antialiased min-h-screen", notoSansJp.className)}>
        <SessionWrapper>
          <Header />
          <Main>
            {children}
          </Main>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
